/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const BlogPost = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
  'date' : Time,
  'tags' : IDL.Vec(IDL.Text),
  'summary' : IDL.Text,
});
export const Education = IDL.Record({
  'endDate' : IDL.Text,
  'institution' : IDL.Text,
  'degree' : IDL.Text,
  'startDate' : IDL.Text,
});

export const idlService = IDL.Service({
  'addBlogPost' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Text],
      [],
      [],
    ),
  'deleteBlogPost' : IDL.Func([IDL.Text], [], []),
  'getAllBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
  'getBlogPost' : IDL.Func([IDL.Text], [BlogPost], ['query']),
  'getBlogPostsByTag' : IDL.Func([IDL.Text], [IDL.Vec(BlogPost)], ['query']),
  'getCoverLetter' : IDL.Func([], [IDL.Text], ['query']),
  'getEducation' : IDL.Func([], [IDL.Vec(Education)], ['query']),
  'getResumeTitle' : IDL.Func([], [IDL.Text], ['query']),
  'getSkills' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'initialize' : IDL.Func(
      [IDL.Text, IDL.Vec(IDL.Text), IDL.Vec(Education), IDL.Text],
      [],
      [],
    ),
  'setCoverLetter' : IDL.Func([IDL.Text], [], []),
  'setEducation' : IDL.Func([IDL.Vec(Education)], [], []),
  'setResumeTitle' : IDL.Func([IDL.Text], [], []),
  'setSkills' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
  'updateBlogPost' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const BlogPost = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
    'date' : Time,
    'tags' : IDL.Vec(IDL.Text),
    'summary' : IDL.Text,
  });
  const Education = IDL.Record({
    'endDate' : IDL.Text,
    'institution' : IDL.Text,
    'degree' : IDL.Text,
    'startDate' : IDL.Text,
  });
  
  return IDL.Service({
    'addBlogPost' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Text],
        [],
        [],
      ),
    'deleteBlogPost' : IDL.Func([IDL.Text], [], []),
    'getAllBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
    'getBlogPost' : IDL.Func([IDL.Text], [BlogPost], ['query']),
    'getBlogPostsByTag' : IDL.Func([IDL.Text], [IDL.Vec(BlogPost)], ['query']),
    'getCoverLetter' : IDL.Func([], [IDL.Text], ['query']),
    'getEducation' : IDL.Func([], [IDL.Vec(Education)], ['query']),
    'getResumeTitle' : IDL.Func([], [IDL.Text], ['query']),
    'getSkills' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'initialize' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Text), IDL.Vec(Education), IDL.Text],
        [],
        [],
      ),
    'setCoverLetter' : IDL.Func([IDL.Text], [], []),
    'setEducation' : IDL.Func([IDL.Vec(Education)], [], []),
    'setResumeTitle' : IDL.Func([IDL.Text], [], []),
    'setSkills' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
    'updateBlogPost' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };