/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BlogPost {
  'title' : string,
  'content' : string,
  'date' : Time,
  'tags' : Array<string>,
  'summary' : string,
}
export interface Education {
  'endDate' : string,
  'institution' : string,
  'degree' : string,
  'startDate' : string,
}
export type Time = bigint;
export interface _SERVICE {
  'addBlogPost' : ActorMethod<
    [string, string, Array<string>, string],
    undefined
  >,
  'deleteBlogPost' : ActorMethod<[string], undefined>,
  'getAllBlogPosts' : ActorMethod<[], Array<BlogPost>>,
  'getBlogPost' : ActorMethod<[string], BlogPost>,
  'getBlogPostsByTag' : ActorMethod<[string], Array<BlogPost>>,
  'getCoverLetter' : ActorMethod<[], string>,
  'getEducation' : ActorMethod<[], Array<Education>>,
  'getResumeTitle' : ActorMethod<[], string>,
  'getSkills' : ActorMethod<[], Array<string>>,
  'initialize' : ActorMethod<
    [string, Array<string>, Array<Education>, string],
    undefined
  >,
  'setCoverLetter' : ActorMethod<[string], undefined>,
  'setEducation' : ActorMethod<[Array<Education>], undefined>,
  'setResumeTitle' : ActorMethod<[string], undefined>,
  'setSkills' : ActorMethod<[Array<string>], undefined>,
  'updateBlogPost' : ActorMethod<
    [string, string, Array<string>, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];